version: '3.8'

services:

  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: "sh"
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    volumes:
        - ./:/app
    ports:
      - 3000:3000
    environment:
      PORT: 3000
    networks:
      - default
networks:
  default:
    name: localdev

